export default {
  "topic": "morse_basic",
  "title": "Bảng mã Morse cơ bản",
  "entries": [
    { "code": ".-", "character": "A", "description": "A gồm tích - tà." },
    { "code": "-...", "character": "B", "description": "B gồm tà - tích - tích - tích." },
    { "code": "-.-.", "character": "C", "description": "C gồm tà - tích - tà - tích." },
    { "code": "-..", "character": "D", "description": "D gồm tà - tích - tích." },
    { "code": ".", "character": "E", "description": "E gồm một tích." },
    { "code": "..-.", "character": "F", "description": "F gồm tích - tích - tà - tích." },
    { "code": "--.", "character": "G", "description": "G gồm tà - tà - tích." },
    { "code": "....", "character": "H", "description": "H gồm bốn tích." },
    { "code": "..", "character": "I", "description": "I gồm hai tích." },
    { "code": ".---", "character": "J", "description": "J gồm tích - tà - tà - tà." },
    { "code": "-.-", "character": "K", "description": "K gồm tà - tích - tà." },
    { "code": ".-..", "character": "L", "description": "L gồm tích - tà - tích - tích." },
    { "code": "--", "character": "M", "description": "M gồm hai tà." },
    { "code": "-.", "character": "N", "description": "N gồm tà - tích." },
    { "code": "---", "character": "O", "description": "O gồm ba tà." },
    { "code": ".--.", "character": "P", "description": "P gồm tích - tà - tà - tích." },
    { "code": "--.-", "character": "Q", "description": "Q gồm tà - tà - tích - tà." },
    { "code": ".-.", "character": "R", "description": "R gồm tích - tà - tích." },
    { "code": "...", "character": "S", "description": "S gồm ba tích." },
    { "code": "-", "character": "T", "description": "T gồm một tà." },
    { "code": "..-", "character": "U", "description": "U gồm tích - tích - tà." },
    { "code": "...-", "character": "V", "description": "V gồm tích - tích - tích - tà." },
    { "code": ".--", "character": "W", "description": "W gồm tích - tà - tà." },
    { "code": "-..-", "character": "X", "description": "X gồm tà - tích - tích - tà." },
    { "code": "-.--", "character": "Y", "description": "Y gồm tà - tích - tà - tà." },
    { "code": "--..", "character": "Z", "description": "Z gồm tà - tà - tích - tích." }
  ]
};
