export default {
  "topic": "morse_basic",
  "title": "Bảng mã Morse cơ bản",
  "entries": [
    { "character": "A", "code": ".-", "description": "A gồm tích - ta.", "pronunciation": "An Châu" },
    { "character": "B", "code": "-...", "description": "B gồm ta - tích - tích - tích.", "pronunciation": "Bắc Cạn" },
    { "character": "C", "code": "-.-.", "description": "C gồm ta - tích - ta - tích.", "pronunciation": "Cao Bằng" },
    { "character": "D", "code": "-..", "description": "D gồm ta - tích - tích.", "pronunciation": "Đáp cầu" },
    { "character": "E", "code": ".", "description": "E gồm một tích — ký tự ngắn nhất trong Morse.", "pronunciation": "Em bé" },
    { "character": "F", "code": "..-.", "description": "F gồm tích - tích - ta - tích.", "pronunciation": "Phai phô" },
    { "character": "G", "code": "--.", "description": "G gồm ta - ta - tích.", "pronunciation": "Gò Công" },
    { "character": "H", "code": "....", "description": "H gồm bốn tích.", "pronunciation": "Hà Nội" },
    { "character": "I", "code": "..", "description": "I gồm hai tích.", "pronunciation": "I tờ" },
    { "character": "J", "code": ".---", "description": "J gồm tích - ta - ta - ta.", "pronunciation": "Ji va" },
    { "character": "K", "code": "-.-", "description": "K gồm ta - tích - ta.", "pronunciation": "Kiến An" },
    { "character": "L", "code": ".-..", "description": "L gồm tích - ta - tích - tích.", "pronunciation": "Lạng Sơn" },
    { "character": "M", "code": "--", "description": "M gồm hai ta.", "pronunciation": "Móng Cái" },
    { "character": "N", "code": "-.", "description": "N gồm ta - tích.", "pronunciation": "Nam Định" },
    { "character": "O", "code": "---", "description": "O gồm ba ta.", "pronunciation": "O Tròn" },
    { "character": "P", "code": ".--.", "description": "P gồm tích - ta - ta - tích.", "pronunciation": "Phú Thọ" },
    { "character": "Q", "code": "--.-", "description": "Q gồm ta - ta - tích - ta.", "pronunciation": "Quảng Bình" },
    { "character": "R", "code": ".-.", "description": "R gồm tích - ta - tích.", "pronunciation": "Rạch Giá" },
    { "character": "S", "code": "...", "description": "S gồm ba tích.", "pronunciation": "Sơn Tây" },
    { "character": "T", "code": "-", "description": "T gồm một ta — ký tự ngắn thứ hai.", "pronunciation": "Thái Nguyên" },
    { "character": "U", "code": "..-", "description": "U gồm tích - tích - ta.", "pronunciation": "Uông Bí" },
    { "character": "V", "code": "...-", "description": "V gồm tích - tích - tích - ta.", "pronunciation": "Việt Trì" },
    { "character": "W", "code": ".--", "description": "W gồm tích - ta - ta.", "pronunciation": "Vê Đôi" },
    { "character": "X", "code": "-..-", "description": "X gồm ta - tích - tích - ta.", "pronunciation": "Xiêng Khoảng" },
    { "character": "Y", "code": "-.--", "description": "Y gồm ta - tích - ta - ta.", "pronunciation": "Yên Bái" },
    { "character": "Z", "code": "--..", "description": "Z gồm ta - ta - tích - tích.", "pronunciation": "Zíc Zắc" },

    { "character": "0", "code": "-----", "description": "Số 0 gồm năm ta.", "pronunciation": "Không" },
    { "character": "1", "code": ".----", "description": "Số 1 gồm một tích và bốn ta.", "pronunciation": "Một" },
    { "character": "2", "code": "..---", "description": "Số 2 gồm hai tích và ba ta.", "pronunciation": "Hai" },
    { "character": "3", "code": "...--", "description": "Số 3 gồm ba tích và hai ta.", "pronunciation": "Ba" },
    { "character": "4", "code": "....-", "description": "Số 4 gồm bốn tích và một ta.", "pronunciation": "Bốn" },
    { "character": "5", "code": ".....", "description": "Số 5 gồm năm tích.", "pronunciation": "Năm" },
    { "character": "6", "code": "-....", "description": "Số 6 gồm một ta và bốn tích.", "pronunciation": "Sáu" },
    { "character": "7", "code": "--...", "description": "Số 7 gồm hai ta và ba tích.", "pronunciation": "Bảy" },
    { "character": "8", "code": "---..", "description": "Số 8 gồm ba ta và hai tích.", "pronunciation": "Tám" },
    { "character": "9", "code": "----.", "description": "Số 9 gồm bốn ta và một tích.", "pronunciation": "Chín" }
  ]
};
