export default {
  "topic": "morse_basic",
  "title": "Bảng mã Morse cơ bản",
  "entries": [
    { "character": "A", "code": ".-", "description": "A gồm tích - tà.", "keywords": ["alpha", "á"], "example": "A thường xuất hiện trong tên gọi và địa chỉ" },
    { "character": "B", "code": "-...", "description": "B gồm tà - tích - tích - tích.", "keywords": ["bravo"], "example": "B hay gặp trong chữ B corresponds" },
    { "character": "C", "code": "-.-.", "description": "C gồm tà - tích - tà - tích.", "keywords": ["charlie", "cao", "liên lạc"], "example": "C là thành phần của CQ — tín hiệu gọi chung" },
    { "character": "D", "code": "-..", "description": "D gồm tà - tích - tích.", "keywords": ["delta"], "example": "D xuất hiện nhiều trong từ BufferedWriter" },
    { "character": "E", "code": ".", "description": "E gồm một tích — ký tự ngắn nhất trong Morse.", "keywords": ["echo", "ngắn nhất"], "example": "E là ký tự phổ biến nhất trong tiếng Anh" },
    { "character": "F", "code": "..-.", "description": "F gồm tích - tích - tà - tích.", "keywords": ["foxtrot"], "example": "F thường dùng trong tên riêng" },
    { "character": "G", "code": "--.", "description": "G gồm tà - tà - tích.", "keywords": ["golf"], "example": "G xuất hiện trong từ good" },
    { "character": "H", "code": "....", "description": "H gồm bốn tích.", "keywords": ["hotel", "tứ"], "example": "H là phổ biến trong giao tiếp hàng ngày" },
    { "character": "I", "code": "..", "description": "I gồm hai tích.", "keywords": ["india"], "example": "I là đại từ nhân xưng phổ biến" },
    { "character": "J", "code": ".---", "description": "J gồm tích - tà - tà - tà.", "keywords": ["juliet"], "example": "J ít xuất hiện hơn trong giao tiếp" },
    { "character": "K", "code": "-.-", "description": "K gồm tà - tích - tà.", "keywords": ["kilo", "phản hồi"], "example": "K dùng làm tín hiệu 'phản hồi' trongprosign" },
    { "character": "L", "code": ".-..", "description": "L gồm tích - tà - tích - tích.", "keywords": ["lima"], "example": "L hay gặp trong từ love, life" },
    { "character": "M", "code": "--", "description": "M gồm hai tà.", "keywords": ["mike"], "example": "M là chữ cái đầu trong Morse" },
    { "character": "N", "code": "-.", "description": "N gồm tà - tích.", "keywords": ["november"], "example": "N xuất hiện trong negation" },
    { "character": "O", "code": "---", "description": "O gồm ba tà.", "keywords": ["oscar", "ba tà"], "example": "O là thành phần SOS: ...---..." },
    { "character": "P", "code": ".--.", "description": "P gồm tích - tà - tà - tích.", "keywords": ["papa"], "example": "P thường dùng trong phường/phe" },
    { "character": "Q", "code": "--.-", "description": "Q gồm tà - tà - tích - tà.", "keywords": ["quebec", "gọi chung"], "example": "Q là thành phần CQ — tín hiệu gọi chung cho tất cả trạm" },
    { "character": "R", "code": ".-.", "description": "R gồm tích - tà - tích.", "keywords": ["romeo", "nhận"], "example": "R dùng làm tín hiệu 'đã nhận' trong giao tiếp" },
    { "character": "S", "code": "...", "description": "S gồm ba tích.", "keywords": ["sierra", "sos"], "example": "S là thành phần SOS: ...---..." },
    { "character": "T", "code": "-", "description": "T gồm một tà — ký tự ngắn thứ hai.", "keywords": ["tango", "tà"], "example": "T là điểm bắt đầu của nhiều từ" },
    { "character": "U", "code": "..-", "description": "U gồm tích - tích - tà.", "keywords": ["uniform"], "example": "U xuất hiện trong từ unified" },
    { "character": "V", "code": "...-", "description": "V gồm tích - tích - tích - tà.", "keywords": ["victor", "chiến thắng"], "example": "V là tín hiệu chiến thắng: ...- (V for Victory)" },
    { "character": "W", "code": ".--", "description": "W gồm tích - tà - tà.", "keywords": ["whiskey"], "example": "W dùng trong tên riêng và từ khóa" },
    { "character": "X", "code": "-..-", "description": "X gồm tà - tích - tích - tà.", "keywords": ["x-ray"], "example": "X ít dùng, thường trong tên riêng" },
    { "character": "Y", "code": "-.--", "description": "Y gồm tà - tích - tà - tà.", "keywords": ["yankee"], "example": "Y xuất hiện trong câu hỏi yes/no" },
    { "character": "Z", "code": "--..", "description": "Z gồm tà - tà - tích - tích.", "keywords": ["zulu"], "example": "Z thường dùng trong múi giờ Zulu" },

    { "character": "0", "code": "-----", "description": "Số 0 gồm năm tà.", "keywords": ["số không", "zero", "0"], "example": "0 dùng trong số điện thoại, tần số" },
    { "character": "1", "code": ".----", "description": "Số 1 gồm một tích followed by bốn tà.", "keywords": ["số một", "one", "1"], "example": "1 thường xuất hiện trong số hiệu" },
    { "character": "2", "code": "..---", "description": "Số 2 gồm hai tích followed by ba tà.", "keywords": ["số hai", "two", "2"], "example": "2 dùng trong tần số, kênh" },
    { "character": "3", "code": "...--", "description": "Số 3 gồm ba tích followed by hai tà.", "keywords": ["số ba", "three", "3"], "example": "3 xuất hiện trong số đếm" },
    { "character": "4", "code": "....-", "description": "Số 4 gồm bốn tích followed by một tà.", "keywords": ["số bốn", "four", "4"], "example": "4 dùng trong tần số" },
    { "character": "5", "code": ".....", "description": "Số 5 gồm năm tích.", "keywords": ["số năm", "five", "5"], "example": "5 là số tích nhiều nhất" },
    { "character": "6", "code": "-....", "description": "Số 6 gồm một tà followed by bốn tích.", "keywords": ["số sáu", "six", "6"], "example": "6 dùng trong đếm số" },
    { "character": "7", "code": "--...", "description": "Số 7 gồm hai tà followed by ba tích.", "keywords": ["số bảy", "seven", "7"], "example": "7 xuất hiện trong số đo" },
    { "character": "8", "code": "---..", "description": "Số 8 gồm ba tà followed by hai tích.", "keywords": ["số tám", "eight", "8"], "example": "8 dùng trong tần số" },
    { "character": "9", "code": "----.", "description": "Số 9 gồm bốn tà followed by một tích.", "keywords": ["số chín", "nine", "9"], "example": "9 thường cuối dãy số" }
  ]
};
